apiVersion: core.oam.dev/v1alpha1
kind: Trait
metadata:
  name: rollout
spec:
  appliesTo:
    - core.oam.dev/v1alpha1.Server
  properties: >
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object"
      "properties": {
        "canaryReplicas": {
          "type" : "number"
          "description": "canary replicas when rollout"
        },
        "batches": {
          "type": "number",
          "description": "batch times, if canary replicas is not 0, batch rollout for remain replicas."
        },
        "batchInterval": {
          "type": "number",
          "description": "interval time in second between batches."
        },
        "instanceInterval": {
          "type": "number",
          "description": "interval time in second between instances within batch."
        }
      }
    }

---
apiVersion: core.oam.dev/v1alpha1
kind: Trait
metadata:
  name: servicebinding
spec:
  appliesTo:
    - core.oam.dev/v1alpha1.Server
  properties: |
    {
      "type": "object"
      "properties": {
        "servicebindings": {
          "type": "array"
          "items": {
            "type": "object",
            "properties": {
              "objectRef": {
                "$ref": "#/definitions/ObjectReference"
              }
            }
          }
        },
      }
      "definitions": {
        "ObjectReference": {
          "properties": {
            "kind": {
              "type": "string"
            },
            "namespace": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "uid": {
              "type": "string"
            },
            "apiVersion": {
              "type": "string"
            },
            "resourceVersion": {
              "type": "string"
            },
            "fieldPath": {
              "type": "string"
            }
          }
        }
      }
    }